development:
  adapter: postgresql
  database: suggestotron_development
  host: localhost
  port: <%= ENV['GH_POSTGRESQL_PORT'] %>
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: suggestotron_test
  pool: 5
  timeout: 5000
  host: localhost
  port: <%= ENV['GH_POSTGRESQL_PORT'] %>

